### ISSUE TITLE
[BUG] Stav did an oopsie (1.20.1)

### ISSUE THREAD

**Issue by mindryder** [StavWasPlayZ/Genshin-Instruments-Fabric#1]
1.20.1 fabric, dont work.

**Comment by StavWasPlayZ** [comment]
Hey there, mindryder. Please leave your `debug.log` so I can look into it.

Thanks.

**Comment by StavWasPlayZ** [comment]
For the lack of response, I shall assume that the problem is no more and will be closing this issue.
