### ISSUE TITLE
[BUG] Registered packets are being localized

### ISSUE THREAD

**Issue by Krezz23** [StavWasPlayZ/Genshin-Instruments-Fabric#3]
[crash-2024-06-14_18.23.03-client.txt](https://github.com/user-attachments/files/15840843/crash-2024-06-14_18.23.03-client.txt)

It crashes due to "net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: genshinstrument:\u0131nstrumentpacket"

**Comment by StavWasPlayZ** [comment]
Hey there, thanks for the report! Apologies for the inconvenience. I'll push a bugfix for this issue in v4.0 (should be out in mid-to-early July).

I see that your PC uses Turkish as your OS' language?  
The error seems to stem from the JVM converting lowercase `"i"` to `"ı"` - which is an i without the dot on top. Though seemingly the same letter, it is, in fact, completely different for our dummy computers.  
Again, will fix it - but you could change language in the meantime if you'd prefer an immediate fix. 🙃

Thanks again!

**Comment by StavWasPlayZ** [comment]
*didnt mean to close whoops

**Comment by StavWasPlayZ** [comment]
Should be fixed with the upcoming Genshin Instruments v4.0.
